spring.application.name=tax-service

# ✅ PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/taxdb
spring.datasource.username=postgres
spring.datasource.password=@Hari123

# ✅ JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ✅ Server
server.port=8080

# ✅ Security (same as before)
spring.security.user.name=admin
spring.security.user.password=admin123